### ISSUE TITLE
Error with realtex sound card

### ISSUE THREAD

**Issue by bace1996** [Incubator113704/SampleRatesAutoSwitcher#1]
i run this demo like this
SampleRateSwitcher.exe 1 b
but it open my audio option than i get an error
Error: Could not find the "Handle of audio device properties dialog", confirm problem and close the program
what should i do?

**Comment by Incubator113704** [comment]
Issue confirmed

The reason is not any audio device has three tab and not any second tab is the "Advanced" to change sample rates.
Will be fix it in next release soon, thank you for the information.
1.0.1 will add this parameters to config file "Constants.txt, key index 15, you just modify it from 2 to 3
